# Generated by Django 5.2.17 on 2026-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('line', 'LINE'), ('webform', 'Web form')], max_length=20)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('auto_reply', 'Auto reply'), ('escalation', 'Escalation')], max_length=20)),
                ('generated_reply', models.TextField()),
                ('matched_knowledge', models.CharField(blank=True, max_length=255)),
                ('escalation_target', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
